### ISSUE TITLE
Sound stopped when source/listener is not in line of sight

### ISSUE THREAD

**Issue by dingzeyuli** [EVERTims/evertims#4]
In this blender file, the geometry is a room connected to a long hallway. 
[complex_room.blend.zip](https://github.com/EVERTims/evertims/files/974807/complex_room.blend.zip)

The sound engine works fine when the source is in the line of sight of the listener. Like the two images below, these two configuration would give me a reasonable sound output.

![Working OK 1.](https://cloud.githubusercontent.com/assets/5297902/25683712/7dd854a2-302b-11e7-97ab-c0d1918244d0.png)
![Working OK 2.](https://cloud.githubusercontent.com/assets/5297902/25683711/7dd5c0b6-302b-11e7-86be-4bf452c12f25.png)

However, when I move the source further, the sound suddenly stopped. Same thing happens if I move the source to the right hallway. 
![Not working 3.](https://cloud.githubusercontent.com/assets/5297902/25683764/bdb64958-302b-11e7-9111-eaf933b04b2f.png)

**Comment by PyrApple** [comment]
Your room material is set to "absorber", hence nothing but the direct path will be rendered, non-existent in the latest config. See the [EVERTims v0.3 demo video](https://youtu.be/EJ-GHdC7-eo?t=230) for an example of how to set you room's materials. Let me know if you want the mod. model as a .zip here.

**Comment by dingzeyuli** [comment]
Yes, I also realized that. Thank you! May I ask where is the testIRs.m file? I would like to try that as well.

**Comment by PyrApple** [comment]
https://github.com/EVERTims/auralization_engine_evertims/tree/master/Utils/testIRs
