### ISSUE TITLE
Compiling Error - bsd/stdlib.h

### ISSUE THREAD

**Issue by oliverman54** [EVERTims/evertims#9]
Hello,
I am not very experienced with compiling programs, but I'd really like to try out this software.
When I try to run the linux build script it calls for the bsd/stdlib.h file. It refuses to continue (obviously) Why is this file required? Is my C++ installation misconfigured somehow? I'm not sure.
I know this may not be a specific issue with your program, but I'm out of ideas.

**Comment by fhubau** [comment]
You are missing the libbsd library. Just run sudo apt-get install libbsd-dev and it should be fixed.
